import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const cabinetGrotesk = localFont({
    src: [
        {
            path: "../../public/fonts/Cabinet-Grotesk/CabinetGrotesk-Variable.woff2",
            style: "normal",
            weight: "100 900",
        },
        {
            path: "../../public/fonts/Cabinet-Grotesk/CabinetGrotesk-Variable.woff",
            style: "normal",
            weight: "100 900",
        },
    ],
    variable: "--font-cabinet",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${cabinetGrotesk.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
